lines/urls.py
from django.urls import path

from . import views

app_name = 'lines'
urlpatterns = [
    path('<str:folder>', views.index, name='index'),
    path('<str:folder>/<int:begin>/<int:end>', views.index, name='index'),
    path('move/<str:folder>/<int:begin>/<int:end>', views.move, name='move')
]

list/urls.py
from django.urls import path

from . import views

app_name = 'list'
urlpatterns = [
    path('<str:folder>', views.index, name='index'),
    path('<str:folder>/<int:begin>/<int:end>', views.index, name='index'),
    path('move/<str:folder>/<int:begin>/<int:end>', views.move, name='move')
]

picSorter/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('list/', include('list.urls', namespace='list')),
    path('lines/', include('lines.urls', namespace='lines')),
    path('admin/', admin.site.urls),
]

lines/models.py
from django.db import models

# Create your models here.

list/models.py
from django.db import models

# Create your models here.

lines/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.conf import settings
import os

FOLDERS = {'1': "Handwritten",
           '2': "Typescript",
           '3': "Bad",
           '4': "Multiples_Lines"}


def index(request, begin=0, end=50, folder=""):
    begin = int(begin)
    end = int(end)
    base_path = os.path.join(settings.BASE_DIR, "lines/static/lines/", folder)

    # list all the files alphabetically and excludes folders
    files = sorted(os.listdir(base_path))
    files = [file for file in files
             if os.path.isfile(os.path.join(base_path, file))]

    # Only keep the files in a certain range
    end = min(end, len(files))
    files = files[begin:end]

    folders_path = []
    score = {}
    # Create the folder that will store the sorted files (if they do not exist)
    # and count the files in them
    for key in FOLDERS.keys():
        folder_path = os.path.join(base_path, FOLDERS[key])
        if not os.path.exists(folder_path):
            os.makedirs(folder_path)
        folders_path.append(os.path.join(folder_path))
        score[FOLDERS[key]] = len(os.listdir(folder_path))
    # Convert scores to percentages
    score['Total'] = sum(score.values())
    for key in score.keys():
        if key != 'Total':
            score[key] = "{:.3}".format((score[key] / score['Total']) * 100)
    # Sort the dict to keep the button in the same order
    sort_folders = [(key, FOLDERS[key]) for key in FOLDERS.keys()]
    sort_folders = sorted(sort_folders, key=lambda t: t[0])


    pics = ["lines/{}/{}".format(folder, file) for file in files]
    context = {'lists': sorted(pics), 'begin': begin, 'end': end,
               'score': score, 'folder': folder, 'sort_folders': sort_folders}
    return render(request, 'lines/index.html', context)


def move(request, begin, end, folder):
    path = os.path.join(settings.BASE_DIR, "lines/static/lines/", folder)

    # Get all files selected
    items = [item for item in request.POST.items()
             if item[1] in FOLDERS.keys()]
    # item is formatted like that :
    # (filename, key)
    for item in items:
        print(item[0])
        filename = item[0].split("/")[-1]
        os.rename(os.path.join(path, filename),
                  os.path.join(path, FOLDERS[item[1]], filename))
    return HttpResponseRedirect(reverse('lines:index',
                                        kwargs={'begin': begin,
                                                'end': end,
                                                'folder': folder}
                                        ))

list/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.conf import settings
import os
import sys


def index(request, begin=0, end=50, folder=""):
    begin = int(begin)
    end = int(end)
    path = os.path.join(settings.BASE_DIR, "list/static/list/", folder)
    files = sorted(os.listdir(path))[begin:end]

    bad_path = os.path.join(path, "sorted")
    if not os.path.exists(bad_path):
        os.makedirs(bad_path)

    path = os.path.join(settings.BASE_DIR, "list/static/list/",
                        folder, "sorted")
    score = len(os.listdir(path))

    pics = ["list/{}/{}".format(folder, file) for file in files]
    context = {'lists': sorted(pics), 'begin': begin, 'end': end,
               'score': score, 'folder': folder}
    return render(request, 'list/index.html', context)


def move(request, begin, end, folder):
    path = os.path.join(settings.BASE_DIR, "list/static/list/")

    for file in request.POST.getlist('files'):
        filename = file.split("/")[-1]
        os.rename(os.path.join(path, folder, filename),
                  os.path.join(path, folder, "sorted", filename))
    size = int(end) - int(begin)
    return HttpResponseRedirect(reverse('list:index',
                                        kwargs={'begin': end,
                                                'end': int(end) + size,
                                                'folder': folder}
                                        ))

lines/templates/lines/index.html
{% load static %}

<head>
  <link rel="stylesheet" href="{% static "css/lines.css" %}">
</head>

<div class="container">
  <h1>Class the pictures.</h1>
  <p>Select the closest category for the pictures.</p>
  {% for key, name in score.items %}
    <p class="info">{{key}}: {{name}}{% if key != 'Total' %}%{%endif%}</p>
  {% endfor %}

  <form action="{% url 'lines:move' begin=begin end=end folder=folder%}" method="post">
  {% csrf_token %}
    {% for l in lists %}
      <div class="imgContainer">
        <img src="{% static l %}"/>
        <div class="choices">
          {% for key, name in sort_folders %}
            <input type="radio" name="{{l}}" id="{{key}}{{l}}" value="{{key}}">
            <label for="{{key}}{{l}}">
              {{name}}
            </label>
          {% endfor %}
        </div>
      </div>
    {% endfor %}
    <input class="submitBtn" type="submit" value="Submit">
  </form>
</div>

list/templates/list/index.html
{% load static %}

<head>
  <link rel="stylesheet" href="{% static "css/list.css" %}">
</head>

<div class="container">
  <p class="info"> You've sorted {{score}} bad files</p>
  <form action="{% url 'list:move' folder=folder begin=begin end=end%}" method="post">
  {% csrf_token %}
    {% for l in lists %}
    <label class="selectableImg">
      <input type="checkbox" name="files" value="{{l}}">
      <img src="{% static l %}"/>
    </label>
    {% endfor %}
    <input class="submitBtn" type="submit" value="Submit">
  </form>
</div>